### ISSUE TITLE
bedlevel-v2 compiling

### ISSUE THREAD

**Issue by epicac** [Printrbot/Marlin#1]
Seems to be some issue during compiling. The provided v2 .hex file flashes fine, but if you try and compile v2 from the provided source, the created .hex won't flash. I tried this with both Flip and the Mac Firmware updater. I get the error "Bootloader and code overlap." I can edit, compile, and flash v1 just fine.

**Comment by PxT** [comment]
Same here. @lwalkera can you comment on how the provided hex was compiled?

**Comment by lwalkera** [comment]
I compiled it with the Linux version of Arduino 1.0.5 with the version of Teensyduino from Jan 16

**Comment by noopkat** [comment]
I am also having the same problem, any updates on this? The source compiles on OSX Arduino 1.0.5, latest version of Teensyduino at 346KB. The precompiled hex from the release is 343KB. Weird.

**Comment by scotty1024** [comment]
Since this issue is about problems compiling the code... there is a bug in the provided Makefile:

```
diff --git a/Marlin/Makefile b/Marlin/Makefile
index fd7db37..c73aac2 100644
--- a/Marlin/Makefile
+++ b/Marlin/Makefile
@@ -240,7 +240,8 @@ CXXSRC = WMath.cpp WString.cpp Print.cpp Marlin_main.cpp    
        MarlinSerial.cpp Sd2Card.cpp SdBaseFile.cpp SdFatUtil.cpp       \
        SdFile.cpp SdVolume.cpp motion_control.cpp planner.cpp          \
        stepper.cpp temperature.cpp cardreader.cpp ConfigurationStore.cpp \
-       watchdog.cpp SPI.cpp Servo.cpp Tone.cpp ultralcd.cpp
+       watchdog.cpp SPI.cpp Servo.cpp Tone.cpp ultralcd.cpp \
+       vector_3.cpp qr_solve.cpp
```

The bed leveling code won't link via make on an OctoPrint Raspberry Pi using avr tool chain without that update.

**Comment by mickbalaban** [comment]
is this still an issue?
