### ISSUE TITLE
OPTION 81 FOR PRINTRBOARD REV A-E!!?!?!!

### ISSUE THREAD

**Issue by secretgspot** [Printrbot/Marlin#19]
Do you even check before uploading firmware?   As is by default it fails to compile and if I select 81 for board type it also fails to compile.   What gives?

**Comment by lwalkera** [comment]
Did you install Teensyduino first?

**Comment by secretgspot** [comment]
@lwalkera  umm DUUUH!  so no solution, only smart-ass remarks and closing issues, huh?!?
