### ISSUE TITLE
Question about adding PB USB IDs

### ISSUE THREAD

**Issue by nathan-liyiming** [Printrbot/Marlin#2]
Click the link: https://github.com/Printrbot/Marlin/releases/tag/bedlevel-v2, ~.hex works well for my 3D printer. But, I need to modify this firmware. I have downloaded the source code and modify them, then use arduino to compile it. However, when flashing my 3D printer by my new ~.hex file, I cannot find driver for printer. This is because vid and pid are not correct. So, my question is how to add PB USB IDs during compiling to ~.hex file. Thanks.

**Comment by nathan-liyiming** [comment]
board teensylu/printrboard, uses \hardware\at90usb1286\cores\usb_serial\usb_private.h

**Comment by mickbalaban** [comment]
you can change the pid/vid in the file you listed above. Here is the list of pids for different models:
https://docs.google.com/spreadsheets/d/1TRFRFH8Rd1WQS48TlTFyBGOOjMQJOIu-xmxYJVp4lfQ/edit
