### ISSUE TITLE
Can someone suggest the best branch for a RevB Printrbot Plus board

### ISSUE THREAD

**Issue by pcarew** [Printrbot/Marlin#22]
I'm rebuilding my original Printrbot Plus (Kickstarter) and would like to modify the firmware.
Even though we are 5yrs past the original release of the RevB printrboard, I'm assuming that there is a branch or tag that would be compatible.

Can anyone suggest what would be the most appropriate to try?
Thanks
Paul@CarewContact.com

**Comment by PxT** [comment]
I think you want Unified v3:  https://github.com/Printrbot/Marlin/releases/tag/unified-v3

**Comment by pcarew** [comment]
Thankyou
