### ISSUE TITLE
G29 Non Op on PrintrBot Simple Maker 1402

### ISSUE THREAD

**Issue by dataman** [Printrbot/Marlin#24]
PrintrBot Simple Maker 1402
Upgrade to Rev F board
Flashed with PrintrBot Firmware Updater

Startup code reads:
G28 X0 Y0 Z0
G29

Printer ignores G29, 
Homes to  x0, y0
Z Homes, then raises,
Extrudes, 
Then homes to center.

This is causing serious issues.
Head is too high at rear of print and too close at front.
How can I get G29 working again?

**Comment by mickbalaban** [comment]
I just took a quick glance at G29 command in marlin_main file https://github.com/Printrbot/Marlin/blob/c06b9dee23b4f4fa6171670e9727880744d4f618/src/Marlin_main.cpp#L1363

and I see that this command is ignored if ENABLE_AUTO_BED_LEVELING is not set. I am not sure if that is the case here.

**Comment by dataman** [comment]
I found a precompiled version at: https://www.reddit.com/r/PrintrBot/comments/2cxodz/auto_level_on_simple_makers_works_too_well/cjk8s66/

However I will try to re-compile with that def.
It's about high time that I learned how to compile Marlin.

**Comment by mickbalaban** [comment]
You can also try official printrbot image, which you can install with  http://printrbot.com/firmware/ and maybe close this issue if it is not related to official firmware (in this repo)

**Comment by dataman** [comment]
Sadly, this is broken in the PrintrBot image and they are not talk to me.  I will close this out as known Printrbot Issue,

**Comment by mickbalaban** [comment]
Can you explain more what is broken in printrbot image? Is the auto leveling not working with one of the images provided here: https://github.com/Printrbot/firmware-updater/tree/gh-pages/binaries

**Comment by dataman** [comment]
Exactly.  Printrbot Simple does not autolevel.  As these bots were designed without the ability to adjust the bed, autolevel is critical to operation.  I believe there is a simple code change and I’m happy to contribute.

Sent from my iPhone 7!
Charley Jones, PMP

**Comment by dataman** [comment]
It’s possible that the current firmware was not compiled with the PB_Simple define.  I used the pb firmware updater to download the most recent version which does not have autolevel.

Sent from my iPhone 7!
Charley Jones, PMP

**Comment by mickbalaban** [comment]
if your simple is not autoleveling with the firmware linked above, then it is probably a hardware issue since that firmware works with probe and has autoleveling enabled by default.

Which firmware updater did you use? Printrbot firmware updater tool uses binary images linked above, and those have probe enabled (except bocussini and mcf builds)

**Comment by dataman** [comment]
I use something called the Printrbot firmware updater tool.  It was published in the forums a while ago and only exists for Mac.  I’d be happy to try with a newer version of the updater.  Never occurred to me that could be the issue.

Sent from my iPhone 7!
Charley Jones, PMP
