### ISSUE TITLE
Please add thermistor tables for Pico Hot end with 500C

### ISSUE THREAD

**Issue by ssa3512** [Printrbot/Marlin#3]
Please add the thermistor tables for the new 500C thermistor from B3Innovations (Marlin table #70)

http://www.b3innovations.com/wp-content/uploads/2014/04/500c-Temp-Table.txt

https://github.com/ErikZalm/Marlin/pull/955

**Comment by lwalkera** [comment]
Please submit a pull request with this implemented.

**Comment by ssa3512** [comment]
Created pull request #4

**Comment by lwalkera** [comment]
Merged request
