### ISSUE TITLE
4 point auto level probing

### ISSUE THREAD

**Issue by bmcminn** [Printrbot/Marlin#5]
Noticed the 3 point auto level setup doesn't account for the back-right-hand side of my aluminum printer bed being higher than the rest when the print gets going. Curious if the algorithm would benefit from a 4 point probe setup to better infer the actual plane of the build platform?

Printrbot Simple Maker's Edition 1405, Firmware: Simple-Metal-1403-Firmware

**Comment by NetForces** [comment]
Just installed the probe on my maker 1312 and noticing the same. Anyway to add a 4 point probe ?

**Comment by controlsfreek** [comment]
3 points should define the plane of the print bed. There are two exceptions i can think of: 1) Your axes are not orthogonal or 2) The print bed is warped (not a flat piece of metal).
If either of those two are true, I don't think a 4th point would be beneficial to the autolevel system- a new calibration feature would need in addition to the autolevel which would correct for these two cases.

**Comment by mickbalaban** [comment]
this is an old issue so I am closing it. If anybody is still interested in adding more probing points to bed leveling, try playing with settings in config.h ACCURATE_BED_LEVELING_POINTS 

https://github.com/Printrbot/Marlin/blob/printrbot-prod/Marlin/Configuration.h#L399
