### ISSUE TITLE
Is this the firmware for the new Metal Plus?

### ISSUE THREAD

**Issue by nylen** [Printrbot/Marlin#8]
If not, where can we get it?

**Comment by AmazingSpanoMan** [comment]
Printrbot.com/metalplus

**Comment by nylen** [comment]
I want the source code that ships with the Metal Plus.  I see the `.hex` file but I don't see a link to the source code there.

**Comment by PxT** [comment]
Source & hex are available at https://github.com/Printrbot/Marlin/releases/tag/RevF-Version-1
